### ISSUE TITLE
extra information on the regions

### ISSUE THREAD

**Issue by asifzubair** [saketkc/gencode_regions#1]
The script looks great.

However, is it possible to get some extra information on the genomic features than just the coordinates ? For example, for the exons, would it be possible to know 
- which gene a particular exon belongs to
- its position in the exon set - first, second ... last 
etc. 

Thanks!

**Comment by saketkc** [comment]
Fixed in https://github.com/saketkc/gencode_regions/commit/323ce04013180ed80fcbe425a3f8b3cf4cd2d4ed

**Comment by asifzubair** [comment]
sorry but i didn't get this [line](https://github.com/saketkc/gencode_regions/blob/master/genepred_to_bed.py#L94). You seem to have the same statement in both the `if` and `else` block.

**Comment by saketkc** [comment]
Will fix it, but that doesn't affect any other steps.

**Comment by saketkc** [comment]
Improved in https://github.com/saketkc/gencode_regions/commit/ca4ceb30966368de7ce3205b9709a24545976709
