### ISSUE TITLE
Promoters?

### ISSUE THREAD

**Issue by c2b2pss** [saketkc/gencode_regions#12]
Hi,

Are promoters also output specifically? It does not seem to be in the master data, nor does it say it is one of the outputs.
I understand that what makes a promoter is variable, but extracting xxx bp upstream/down of TSS would be good enough.

Thanks!

**Comment by saketkc** [comment]
Hi @c2b2pss, yes, promoters are extracted by pullint out +/- 2kb regions from the TSS. For example see: https://github.com/saketkc/gencode_regions/tree/master/data/GRCh38/v25 and the associated notebook:  https://github.com/saketkc/gencode_regions/blob/6e32af220c4d929f3ad67414ab83ecb343180932/notebooks/hg38-v96.ipynb
