### ISSUE TITLE
Not working with gencode.mm10.vM14.annotation.gtf / gff3

### ISSUE THREAD

**Issue by AMChalkie** [saketkc/gencode_regions#2]
/mnts/stemcell-bioinfo/git/gencode_regions/create_regions_from_gencode.R  /mnts/stemcell-bioinfo/genomes/gencode.mm10.vM14.annotation.gtf  /mnts/stemcell-bioinfo/genomes/gencode_mm10.vM14
Import genomic features from the file as a GRanges object ... OK
Prepare the 'metadata' data frame ... OK
Make the TxDb object ... OK
[1] 0
Error in unlist_obj(introns.data) : 
  could not find function "elementNROWS"
Execution halted

# I also checked this wasn't just a GTF issue by trying the same with the equivalent GFF file:
wget ftp://ftp.sanger.ac.uk/pub/gencode/Gencode_mouse/release_M14/gencode.vM14.annotation.gff3.gz
gunzip gencode.vM14.annotation.gff3.gz
mv gencode.vM14.annotation.gff3  /mnts/stemcell-bioinfo/genomes/.

/mnts/stemcell-bioinfo/git/gencode_regions/create_regions_from_gencode.R  /mnts/stemcell-bioinfo/genomes/gencode.vM14.annotation.gff3 /mnts/stemcell-bioinfo/genomes/gencode_mm10.vM14
Import genomic features from the file as a GRanges object ... OK
Prepare the 'metadata' data frame ... OK
Make the TxDb object ... OK
[1] 0
Error in unlist_obj(introns.data) : 
  could not find function "elementNROWS"
Execution halted

**Comment by saketkc** [comment]
You might be using an older version of Bioconductor S4 vectors (`elementNRows` supersedes `elementLengths` which is now deprecated). I would probably do this:
```
$ source("https://bioconductor.org/biocLite.R")
biocLite()                  ## R version 3.0 or later
```
Anyway, I have pushed the bed files corresponding to `gencode.vM14.annotation.gtf` in https://github.com/saketkc/gencode_regions/commit/fef185d97055a8b9d1c7869e0b01e008810f1691 .
