### ISSUE TITLE
can not execute gtfToGenePred

### ISSUE THREAD

**Issue by qicaibiology** [saketkc/gencode_regions#5]
Hi:

I tried to use your code to get UTR and CDS from a gtf file from emsembl. For that, I download the gtfToGenePred file and do the following steps:
``$ chmod +x gtfToGenePred`
`conda install -c bioconda pybedtools
``conda install -c bioconda gffutils`

But when I typed
`$ gtfToGenePred`
`-bash: gtfToGenePred: command not found`

I am running under anaconda3 so the python version is >=3

What is the solution for the first step?

**Comment by saketkc** [comment]
Hi @qicaibiology, have you looked at the notebooks? https://github.com/saketkc/gencode_regions#notebooks 
If you are using python, `gtfToGenePred` is not required. If you can tell me what GTF you are working with, I might be able to generate a new notebook for it. Thanks!

**Comment by qicaibiology** [comment]
> Hi @qicaibiology, have you looked at the notebooks? https://github.com/saketkc/gencode_regions#notebooks
> If you are using python, `gtfToGenePred` is not required. If you can tell me what GTF you are working with, I might be able to generate a new notebook for it. Thanks!

Thanks for your reply. I have seen you have generated some bedfiles. However, I guess that I would use the gtf I have used for mapping. I got my gtf files from here: https://support.illumina.com/sequencing/sequencing_software/igenome.html. For mice I used Ensembl GRCm38 while for homo sapiens I used ensembl GRCh37. So I tried to generate bed from them?
Thanks again, for your prompt reply

**Comment by saketkc** [comment]
Sure, in that case you will not need `gtfToGenePred`. You can use the notebooks here:
human - https://github.com/saketkc/gencode_regions/blob/master/notebooks/hg38-v96.ipynb
mouse - https://github.com/saketkc/gencode_regions/blob/master/notebooks/mm10.ipynb
to get the relevant bed files.

You will need to install `pybedtools`, `gffutils` and `pandas` using `pip`.

**Comment by qicaibiology** [comment]
> Sure, in that case you will not need `gtfToGenePred`. You can use the notebooks here:
> human - https://github.com/saketkc/gencode_regions/blob/master/notebooks/hg38-v96.ipynb
> mouse - https://github.com/saketkc/gencode_regions/blob/master/notebooks/mm10.ipynb
> to get the relevant bed files.
> 
> You will need to install `pybedtools`, `gffutils` and `pandas` using `pip`.

Thanks again for explanation: I am working on server through university Linux system. After I have installed pybedtools/gffutils/pandas, how can I excute the files you listed? I am started to learn this stuffs. So I have to ask a little bit more. (For example when I run a bash file, the format is: `bash xx.sh filename`. What should I type for the scripts you wrote?)

**Comment by saketkc** [comment]
Sure, happy to help! You can use the attached script. Please change the following few lines:

```
gtf = './Homo_sapiens.GRCh38.96.gtf'
gtf_db = '{}.db'.format(gtf)
prefix = './output_beds/'
```

gtf: location to your GTF file
gtf_df: Don't change
prefix: Output directory where you want to output the beds.

You can download the script from here: https://gist.githubusercontent.com/saketkc/d70fbb9f3b611a7c51a48591b35d4d90/raw/e636a0409d42e1fd7237dc76d0acf00c447e69f0/hg38.py

Once you edit the location to `gtf` and `prefix` run it using `python hg38.py`.

Thanks!

**Comment by qicaibiology** [comment]
> Sure, happy to help! You can use the attached script. Please change the following few lines:
> 
> ```
> gtf = './Homo_sapiens.GRCh38.96.gtf'
> gtf_db = '{}.db'.format(gtf)
> prefix = './output_beds/'
> ```
> 
> gtf: location to your GTF file
> gtf_df: Don't change
> prefix: Output directory where you want to output the beds.
> 
> You can download the script from here: https://gist.githubusercontent.com/saketkc/d70fbb9f3b611a7c51a48591b35d4d90/raw/e636a0409d42e1fd7237dc76d0acf00c447e69f0/hg38.py
> 
> Once you edit the location to `gtf` and `prefix` run it using `python hg38.py`.
> 
> Thanks!

Much appreciated. Going to give it a try!

**Comment by qicaibiology** [comment]
> Sure, happy to help! You can use the attached script. Please change the following few lines:
> 
> ```
> gtf = './Homo_sapiens.GRCh38.96.gtf'
> gtf_db = '{}.db'.format(gtf)
> prefix = './output_beds/'
> ```
> 
> gtf: location to your GTF file
> gtf_df: Don't change
> prefix: Output directory where you want to output the beds.
> 
> You can download the script from here: https://gist.githubusercontent.com/saketkc/d70fbb9f3b611a7c51a48591b35d4d90/raw/e636a0409d42e1fd7237dc76d0acf00c447e69f0/hg38.py
> 
> Once you edit the location to `gtf` and `prefix` run it using `python hg38.py`.
> 
> Thanks!

I got an error 

```
> GRCm38_bed.py:17: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
>   from collections import OrderedDict, Callable
> Traceback (most recent call last):
>   File "GRCm38_bed.py", line 260, in <module>
>     renamed_exons = rename_regions(merged_exons, gene_id)
>   File "GRCm38_bed.py", line 187, in rename_regions
>     regions = list(regions)
>   File "/home/caiqi/anaconda3/lib/python3.7/site-packages/gffutils/interface.py", line 1297, in merge
>     current_merged = self._feature_returner(**current_merged)
>   File "/home/caiqi/anaconda3/lib/python3.7/site-packages/gffutils/interface.py", line 242, in _feature_returner
>     return Feature(**kwargs)
> TypeError: __init__() got an unexpected keyword argument 'children'
```

**Comment by saketkc** [comment]
I am not sure I have seen it earlier. Can you try `pip install gffutils==0.9 pybedtools==0.8.0`.
Thanks!

**Comment by qicaibiology** [comment]
> I am not sure I have seen it earlier. Can you try `pip install gffutils==0.9 pybedtools==0.8.0`.
> Thanks!
Thank you, I changed the version and re-ran it
This is the second error:

```
GRCm38_bed.py:17: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  from collections import OrderedDict, Callable
Traceback (most recent call last):
  File "GRCm38_bed.py", line 275, in <module>
    gene_bed = create_bed(gene_list)
  File "GRCm38_bed.py", line 171, in create_bed
    assert len(region.attributes['gene_id']) == 1
AttributeError: 'DefaultOrderedDict' object has no attribute 'attributes'
```

**Comment by saketkc** [comment]
Sorry, I am not able to reproduce this at my end, so I am not sure if I'll  be able to help.

**Comment by qicaibiology** [comment]
> Sorry, I am not able to reproduce this at my end, so I am not sure if I'll be able to help.
Never mind. I am going to see what can I turn to. 
But I want to know you are "Not able to reproduce error or get it through"?

**Comment by saketkc** [comment]
I am not sure if you have done any additional changes to the script. The error implies `region` is not a gffutils object, which is weird.

**Comment by qicaibiology** [comment]
> I am not sure if you have done any additional changes to the script. The error implies `region` is not a gffutils object, which is weird.

No.I only changed the directory of my GTF file. I even put it within the folder. I run it again. And it looks that it will not go through with the same problem. Thank you all the same

**Comment by saketkc** [comment]
In that case, it is likely that your GTF has non-standard features.

**Comment by qicaibiology** [comment]
> In that case, it is likely that your GTF has non-standard features.

OK. May I ask another question: I have used a method here :https://github.com/stephenfloor/extract-transcript-regions. to get the bedfiles. I indeed got it through.  Then I did the following stuff:

$ awk -F '[,]' 'NR>=2{print $2, $3, $4,$5,".", $7}' OFS='\t' All_retained_intron.csv > All_retained_intron.bed
$ bedtools intersect -a GRCm38_genes_introns_bed6.bed -b All_retained_intron.bed > IR_in_intron.bed

WARNING: File GRCm38_genes_introns_bed6.bed has inconsistent naming convention for record: CHR_MG4180_PATCH 109649750 109650579 ENSMUST00000203001_intron 1 +

WARNING: File GRCm38_genes_introns_bed6.bed has inconsistent naming convention for record: CHR_MG4180_PA TCH 109649750 109650579 ENSMUST00000203001_intron 1 +

My search brought me here, so I changed my code following people's instructions here:
$ bedtools intersect -nonamecheck -u -s -a All_retained_intron.bed -b GRCm38_genes_intron_bed6.bed > IR_in_intron.bed

This time there is no error, but the generated file contains nothing!

It looks that my GTF file indeed has some inconsistent naming system. And I know it is not your responsibility to answer this question. 
Thanks  a lot,
